<?php

/**
 * @file
 * Theme functions for the Staffordshire County Council demo theme.
 */

/**
 * Implements hook_views_pre_render().
 */
function staffordshire_scc_views_pre_render($view) {
  // Attach the events library to the events view.
  if ($view->id() === 'localgov_events_listing') {
    $view->element['#attached']['library'][] = 'staffordshire_scc/events';
  }
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function staffordshire_scc_preprocess_node(&$variables) {
  // Attach the publications library to publication nodes.
  if ($variables['node']->bundle() === 'localgov_publication_page' || $variables['node']->bundle() === 'localgov_publication_cover_page') {
    $variables['#attached']['library'][] = 'staffordshire_scc/publications';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the header search block form.
 */
function staffordshire_scc_form_search_block_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['keys']['#attributes']['placeholder'] = t('Search');
}
